# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2da16d4a4f96f1957efc2331679192e27fe1f9b784a7da9823ca09cc9c92ad608c20aa8114835d0484c276807b834361d9119162750c4b17684ea15b8e4a7b2

test:
  secret_key_base: 1dc2c27a87b3bd0f799ac569c1ed69a13c2337b64835b00ae37c229484d53910b06620ad06c7cbd7752b44f4203ee90e15b701180fbd903ab69ee612433079d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
